// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY3W0BJ1sbAMDx99w1prYly6d1r6SB0K0',
    appId: '1:675323492727:web:7e972cfb2fa4ab48a58972',
    messagingSenderId: '675323492727',
    projectId: 'exercicioavaliativo-87397',
    authDomain: 'exercicioavaliativo-87397.firebaseapp.com',
    databaseURL: 'https://exercicioavaliativo-87397-default-rtdb.firebaseio.com',
    storageBucket: 'exercicioavaliativo-87397.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_kSzx-pRCqqrQhvmpw8CJUjypPNYrylE',
    appId: '1:675323492727:android:4989f081bddeca9ea58972',
    messagingSenderId: '675323492727',
    projectId: 'exercicioavaliativo-87397',
    databaseURL: 'https://exercicioavaliativo-87397-default-rtdb.firebaseio.com',
    storageBucket: 'exercicioavaliativo-87397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMQLT-KPJVJrX6_VONUzm91hPlian2lk8',
    appId: '1:675323492727:ios:5b930381e95cf673a58972',
    messagingSenderId: '675323492727',
    projectId: 'exercicioavaliativo-87397',
    databaseURL: 'https://exercicioavaliativo-87397-default-rtdb.firebaseio.com',
    storageBucket: 'exercicioavaliativo-87397.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMQLT-KPJVJrX6_VONUzm91hPlian2lk8',
    appId: '1:675323492727:ios:5b930381e95cf673a58972',
    messagingSenderId: '675323492727',
    projectId: 'exercicioavaliativo-87397',
    databaseURL: 'https://exercicioavaliativo-87397-default-rtdb.firebaseio.com',
    storageBucket: 'exercicioavaliativo-87397.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY3W0BJ1sbAMDx99w1prYly6d1r6SB0K0',
    appId: '1:675323492727:web:511df6ff7ff45192a58972',
    messagingSenderId: '675323492727',
    projectId: 'exercicioavaliativo-87397',
    authDomain: 'exercicioavaliativo-87397.firebaseapp.com',
    databaseURL: 'https://exercicioavaliativo-87397-default-rtdb.firebaseio.com',
    storageBucket: 'exercicioavaliativo-87397.appspot.com',
  );
}
